# ASP.NET Core (.NET Framework)


trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Frontend'
    customRegistry: 'useFeed'
    customFeed: 'fa2f5c30-0913-41ab-80eb-7c17de6b7ba3'
    

- task: gulp@0
  inputs:
    gulpFile: 'Frontend/gulpfile.js'
    targets: 'dist'
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'src/Rasolo.Web/assets'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/assets.zipd).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
