# ASP.NET Core (.NET Framework)


trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NodeTool@0
  inputs:
    versionSpec: '14.17.6'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Frontend'
    

- task: gulp@0
  inputs:
    gulpFile: 'Frontend/gulpfile.js'
    targets: 'dist'
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: 'src/Rasolo.Web/wwwroot/assets'
#     includeRootFolder: true
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/assets.zip'
#     replaceExistingArchive: true

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(Build.BinariesDirectory)'
#     includeRootFolder: true
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
